imports:
    - { resource: config.yml }

# Contao configuration
contao:
    pretty_error_screens: true

# Monolog configuration
monolog:
    handlers:
        contao:
            type: service
            id: contao.monolog.handler
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [400, 401, 403, 404]
        nested:
            type: rotating_file
            max_files: 10
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
        console:
            type: console
