language: php

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

env:
  global:
    - COMPOSER_ALLOW_XDEBUG=0
    - SYMFONY_DEPRECATIONS_HELPER='weak_vendors'

php: 7.2

install:
  - phpenv config-rm xdebug.ini || true
  - composer update $COMPOSER_FLAGS --no-interaction --no-suggest

script:
  - php vendor/bin/phpunit
