language: php

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

env:
  global:
    - COMPOSER_ALLOW_XDEBUG=0
    - SYMFONY_DEPRECATIONS_HELPER='weak_vendors'

jobs:
  include:
    # Latest dependencies with all PHP versions
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2

    # Ignore the platform requirements for the upcoming PHP version
    - php: nightly
      env: COMPOSER_FLAGS='--ignore-platform-reqs'

    # Lowest dependencies with the oldest and latest PHP versions
    - php: 5.6
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.2
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'

  allow_failures:
    - php: nightly

before_install:
  - phpenv config-rm xdebug.ini || true
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  # To be removed when this is resolved: https://github.com/composer/composer/issues/5355
  - if [[ "$COMPOSER_FLAGS" == *"--prefer-lowest"* ]]; then composer update --no-interaction --no-suggest; fi
  - composer update $COMPOSER_FLAGS --no-interaction --no-suggest

script:
  - php vendor/bin/phpunit
