services:
    _defaults:
        autoconfigure: true

    contao.command.contao-setup:
        class: Contao\ManagerBundle\Command\ContaoSetupCommand
        arguments:
            - '%kernel.project_dir%'
            - '%contao.web_dir%'

    contao.command.debug-plugins:
        class: Contao\ManagerBundle\Command\DebugPluginsCommand
        arguments:
            - '@kernel'

    contao.command.install-web-dir:
        class: Contao\ManagerBundle\Command\InstallWebDirCommand
        arguments:
            - '%kernel.project_dir%'
