services:
    _defaults:
        autoconfigure: true

    contao.command.debug-plugins:
        class: Contao\ManagerBundle\Command\DebugPluginsCommand
        arguments:
            - '@kernel'

    contao.command.generate_app_secret:
        class: Contao\ManagerBundle\Command\GenerateAppSecretCommand
        arguments:
            - '%kernel.project_dir%'
            - '%kernel.secret%'

    contao.command.install-web-dir:
        class: Contao\ManagerBundle\Command\InstallWebDirCommand
        arguments:
            - '%kernel.project_dir%'
