services:
    contao_manager.listener.backend_menu_listener:
        class: Contao\ManagerBundle\EventListener\BackendMenuListener
        arguments:
            - '@security.token_storage'
            - '%contao_manager.manager_path%'
        tags:
            - { name: kernel.event_listener, event: contao.backend_menu_build, method: onBuild, priority: -10 }

    contao_manager.listener.initialize_application:
        class: Contao\ManagerBundle\EventListener\InitializeApplicationListener
        arguments:
            - '%kernel.project_dir%'
        tags:
            - { name: kernel.event_listener, event: contao_installation.initialize_application, method: onInitializeApplication, priority: -128 }

    contao_manager.listener.install_command:
        class: Contao\ManagerBundle\EventListener\InstallCommandListener
        arguments:
            - '%kernel.project_dir%'
        tags:
            - { name: kernel.event_listener, event: console.terminate }
