services:
    Contao\ManagerBundle\HttpKernel\JwtManager: '@contao_manager.jwt_manager'

    contao_manager.cache.clear_bundle:
        class: Contao\ManagerBundle\Cache\BundleCacheClearer
        arguments:
            - '@?filesystem'
        tags:
            - kernel.cache_clearer

    contao_manager.controller.debug:
        class: Contao\ManagerBundle\Controller\DebugController
        arguments:
            - '@security.helper'
            - '@request_stack'
            - '@contao_manager.jwt_manager'
        public: true

    contao_manager.jwt_manager:
        public: true
        synthetic: true

    contao_manager.plugin_loader:
        public: true
        synthetic: true

    contao_manager.routing_loader:
        class: Contao\ManagerBundle\Routing\RouteLoader
        arguments:
            - '@routing.loader'
            - '@contao_manager.plugin_loader'
            - '@kernel'
            - '%kernel.project_dir%'
        public: true

    contao_manager.security.logout_handler:
        class: Contao\ManagerBundle\Security\Logout\LogoutHandler
        arguments:
            - '@?contao_manager.jwt_manager'
