services:
    app.doctrine_result_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        arguments:
            - '@doctrine.result_cache_pool'

    app.doctrine_system_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        arguments:
            - '@doctrine.system_cache_pool'
