# Default parameters
parameters:
    database_host: localhost
    database_port: 3306
    database_user: ~
    database_password: ~
    database_name: ~
    mailer_transport: sendmail
    mailer_host: 127.0.0.1
    mailer_user: ~
    mailer_password: ~
    mailer_port: 25
    mailer_encryption: ~
    secret: ThisTokenIsNotSoSecretChangeIt
